project/ml/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('catboost/', views.CatBoost.as_view(), name='catboost'),
    path('snntorch/', views.SNNTorch.as_view(), name='snntorch'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('ml/', include('ml.urls')),
    path('', include('blog.urls')),
    path('account/', include('django.contrib.auth.urls')),
    path('account/', include('account.urls')),
]

project/api/models.py
import pandas as pd
from django.conf import settings
from django.db import models
from django.dispatch import receiver


DATA_PATH = settings.BASE_DIR / 'api' / 'storage' / 'medical_costs_dataset.csv'


class MedicalCostsDataset(models.Model):
    age = models.IntegerField()
    sex = models.CharField(max_length=10)
    bmi = models.FloatField()
    children = models.IntegerField()
    smoker = models.CharField(max_length=5)
    region = models.CharField(max_length=20)
    charges = models.FloatField()


data = pd.read_csv(DATA_PATH).values
medical_costs_data = [
    MedicalCostsDataset(
        age=row[0], 
        sex=row[1], 
        bmi=row[2], 
        children=row[3], 
        smoker=row[4], 
        region=row[5], 
        charges=row[6], 
    ) for row in data
]
MedicalCostsDataset.objects.bulk_create(medical_costs_data)

project/ml/views.py
from django.views import generic
from django.shortcuts import render


class CatBoost(generic.View):
    template_name = 'catboost.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)


class SNNTorch(generic.View):
    template_name = 'snntorch.html'

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

project/ml/templates/catboost.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row p-3">
        <div id="train">
            <h3>Training</h3>
            <form id="form-train" class="m-0" onsubmit="event.preventDefault(); trainRequest();">
                {% csrf_token %}
                <div class="form-input">
                    <label for="id_seed">Seed:</label>
                    <input type="text" name="seed" autofocus="" autocapitalize="none" maxlength="32" required id="id_seed" value="1">
                </div>
                <button class="btn btn-secondary mt-3">Train</button>
            </form>
            <pre id="train_response" style="margin: 1rem 0 0 0;"></pre>
        </div>
        <script>
            function trainRequest() {
                document.querySelector("#train_response").innerHTML = 'Запрос обрабтывается...'

                let form = document.querySelector('#form-train');
                let formData = new FormData(form);

                var data = {};
                for (var [key, value] of formData.entries()) { 
                    data[key] = value;
                }
                var csrf_token = data["csrfmiddlewaretoken"];
                data = JSON.stringify(data);

                var xhr = new XMLHttpRequest();
                var url = '/api/regression/catboost/train/';
                xhr.open("POST", url, true);
                xhr.setRequestHeader("Content-Type", "application/json");
                xhr.setRequestHeader("X-CSRFToken", csrf_token);
                xhr.send(data);
            
                xhr.onreadystatechange = function () {
                    if (xhr.readyState === XMLHttpRequest.DONE) {
                        if (xhr.status === 200) {
                            document.querySelector("#train_response").innerHTML = JSON.stringify(JSON.parse(xhr.responseText), undefined, 2);
                        } else {
                            document.querySelector("#train_response").innerHTML = `Ошибка запроса: ${xhr.status}`;
                        }
                    }
                };
            }
        </script>
    </div>
    <div class="row p-3">
        <div id="predict">
            <h3>Prediction</h3>
            <form id="form-predict" class="m-0" onsubmit="event.preventDefault(); predictRequest();">
                {% csrf_token %}
                <div class="form-input">
                    <label for="id_age">Age:</label>
                    <input type="text" name="age" autofocus="" autocapitalize="none" maxlength="32" required id="id_age" value="19">
                    <label for="id_sex">Sex:</label>
                    <input type="text" name="sex" autofocus="" autocapitalize="none" maxlength="32" required id="id_sex" value="female">
                    <label for="id_bmi">BMI:</label>
                    <input type="text" name="bmi" autofocus="" autocapitalize="none" maxlength="32" required id="id_bmi" value="27.9">
                    <label for="id_children">Children:</label>
                    <input type="text" name="children" autofocus="" autocapitalize="none" maxlength="32" required id="id_children" value="0">
                    <label for="id_smoker">Smoker:</label>
                    <input type="text" name="smoker" autofocus="" autocapitalize="none" maxlength="32" required id="id_smoker" value="yes">
                    <label for="id_region">Region:</label>
                    <input type="text" name="region" autofocus="" autocapitalize="none" maxlength="32" required id="id_region" value="southwest">
                </div>
                <button class="btn btn-secondary mt-3">Predict</button>
            </form>
            <pre id="predict_response" style="margin: 1rem 0 0 0;"></pre>
        </div>
        <script>
            function predictRequest() {
                document.querySelector("#predict_response").innerHTML = 'Запрос обрабтывается...'

                let form = document.querySelector('#form-predict');
                let formData = new FormData(form);

                var data = {};
                for (var [key, value] of formData.entries()) { 
                    data[key] = value;
                }
                var csrf_token = data["csrfmiddlewaretoken"];
                data['age'] = parseInt(data['age']);
                data['bmi'] = parseFloat(data['bmi']);
                data['children'] = parseInt(data['children']);
                data = JSON.stringify(data);

                var xhr = new XMLHttpRequest();
                var url = '/api/regression/catboost/predict/';
                xhr.open("POST", url, true);
                xhr.setRequestHeader("Content-Type", "application/json");
                xhr.setRequestHeader("X-CSRFToken", csrf_token);
                xhr.send(data);
            
                xhr.onreadystatechange = function () {
                    if (xhr.readyState === XMLHttpRequest.DONE) {
                        if (xhr.status === 200) {
                            document.querySelector("#predict_response").innerHTML = JSON.stringify(JSON.parse(xhr.responseText), undefined, 2);
                        } else {
                            document.querySelector("#predict_response").innerHTML = `Ошибка запроса: ${xhr.status}`;
                        }
                    }
                };
            }
        </script>
    </div>
    <div class="row p-3">
        <div id="dataset">
            <h3>Dataset</h3>
            <button class="btn btn-secondary mt-3" onclick="datasetRequest()">Load</button>
            <pre id="dataset_response" style="margin: 1rem 0 0 0;"></pre>
        </div>
        <script>
            function datasetRequest() {
                document.querySelector("#dataset_response").innerHTML = 'Запрос обрабтывается...'

                var xhr = new XMLHttpRequest();
                var url = '/api/regression/catboost/dataset/';
                xhr.open("GET", url, true);
                xhr.setRequestHeader("Content-Type", "application/json");
                xhr.send();
            
                xhr.onreadystatechange = function () {
                    if (xhr.readyState === XMLHttpRequest.DONE) {
                        if (xhr.status === 200) {
                            document.querySelector("#dataset_response").innerHTML = JSON.stringify(JSON.parse(xhr.responseText), undefined, 2);
                        } else {
                            document.querySelector("#dataset_response").innerHTML = `Ошибка запроса: ${xhr.status}`;
                        }
                    }
                };
            }
        </script>
    </div>
</div>
{% endblock content %}

project/ml/templates/snntorch.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row p-3">
        <div id="train">
            <h3>Training</h3>
            <form id="form-train" class="m-0" onsubmit="event.preventDefault(); trainRequest();">
                {% csrf_token %}
                <div class="form-input">
                    <label for="id_seed">Seed:</label>
                    <input type="text" name="seed" autofocus="" autocapitalize="none" maxlength="32" required id="id_seed" value="1">
                    <label for="id_timesteps">Timesteps:</label>
                    <input type="text" name="timesteps" autofocus="" autocapitalize="none" maxlength="32" required id="id_timesteps" value="50">
                    <label for="id_hidden_layer">Hidden Layer:</label>
                    <input type="text" name="hidden_layer" autofocus="" autocapitalize="none" maxlength="32" required id="id_hidden_layer" value="128">
                    <label for="id_max_iteraions">Max Iteraions:</label>
                    <input type="text" name="max_iteraions" autofocus="" autocapitalize="none" maxlength="32" required id="id_max_iteraions" value="150">
                    <label for="id_learning_rate">Learning Rate:</label>
                    <input type="text" name="learning_rate" autofocus="" autocapitalize="none" maxlength="32" required id="id_learning_rate" value="0.001">
                </div>
                <button class="btn btn-secondary mt-3">Train</button>
            </form>
            <pre id="train_response" style="margin: 1rem 0 0 0;"></pre>
            <div id="train_visualize"></div>
        </div>
        <script>
            function trainRequest() {
                document.querySelector("#train_response").innerHTML = 'Запрос обрабтывается...'

                let form = document.querySelector('#form-train');
                let formData = new FormData(form);

                var data = {};
                for (var [key, value] of formData.entries()) { 
                    data[key] = value;
                }
                var csrf_token = data["csrfmiddlewaretoken"];
                data = JSON.stringify(data);

                var xhr = new XMLHttpRequest();
                var url = '/api/regression/snntorch/train/';
                xhr.open("POST", url, true);
                xhr.setRequestHeader("Content-Type", "application/json");
                xhr.setRequestHeader("X-CSRFToken", csrf_token);
                xhr.send(data);
            
                xhr.onreadystatechange = function () {
                    if (xhr.readyState === XMLHttpRequest.DONE) {
                        if (xhr.status === 200) {
                            document.querySelector("#train_response").innerHTML = JSON.stringify(JSON.parse(xhr.responseText), undefined, 2);
                            document.querySelector("#train_visualize").innerHTML = `<img src="data:image/png;base64, ${JSON.parse(xhr.responseText).untrained_model_jpg_bytes}" style="width: 100%;"><img src="data:image/png;base64, ${JSON.parse(xhr.responseText).trained_model_jpg_bytes}" style="width: 100%;">`;
                        } else {
                            document.querySelector("#train_response").innerHTML = `Ошибка запроса: ${xhr.status}`;
                        }
                    }
                };
            }
        </script>
    </div>
    <div class="row p-3">
        <div id="predict">
            <h3>Prediction</h3>
            <form id="form-predict" class="m-0" onsubmit="event.preventDefault(); predictRequest();">
                {% csrf_token %}
                <div class="form-input">
                    <label for="id_features">Feature:</label>
                    <input type="text" name="features" autofocus="" autocapitalize="none" maxlength="128" required id="id_features" value="0.10, 0.11, 0.12">
                </div>
                <button class="btn btn-secondary mt-3">Predict</button>
            </form>
            <pre id="predict_response" style="margin: 1rem 0 0 0;"></pre>
            <div id="predict_visualize"></div>
        </div>
        <script>
            function predictRequest() {
                document.querySelector("#predict_response").innerHTML = 'Запрос обрабтывается...'

                let form = document.querySelector('#form-predict');
                let formData = new FormData(form);

                var data = {};
                for (var [key, value] of formData.entries()) { 
                    data[key] = value;
                }
                var csrf_token = data["csrfmiddlewaretoken"];
                data['features'] = data['features'].replace(/ /g,"").split(",").map(parseFloat);
                data = JSON.stringify(data);

                var xhr = new XMLHttpRequest();
                var url = '/api/regression/snntorch/predict/';
                xhr.open("POST", url, true);
                xhr.setRequestHeader("Content-Type", "application/json");
                xhr.setRequestHeader("X-CSRFToken", csrf_token);
                xhr.send(data);
            
                xhr.onreadystatechange = function () {
                    if (xhr.readyState === XMLHttpRequest.DONE) {
                        if (xhr.status === 200) {
                            document.querySelector("#predict_response").innerHTML = JSON.stringify(JSON.parse(xhr.responseText), undefined, 2);
                            document.querySelector("#predict_visualize").innerHTML = `<img src="data:image/png;base64, ${JSON.parse(xhr.responseText).model_prediction_jpg_bytes}" style="width: 100%;">`;
                        } else {
                            document.querySelector("#predict_response").innerHTML = `Ошибка запроса: ${xhr.status}`;
                        }
                    }
                };
            }
        </script>
    </div>
    <div class="row p-3">
        <div id="dataset">
            <h3>Dataset</h3>
            <button class="btn btn-secondary mt-3" onclick="datasetRequest()">Load</button>
            <pre id="dataset_response" style="margin: 1rem 0 0 0;"></pre>
            <div id="dataset_visualize"></div>
        </div>
        <script>
            function datasetRequest() {
                document.querySelector("#dataset_response").innerHTML = 'Запрос обрабтывается...'

                var xhr = new XMLHttpRequest();
                var url = '/api/regression/snntorch/dataset/';
                xhr.open("GET", url, true);
                xhr.setRequestHeader("Content-Type", "application/json");
                xhr.send();
            
                xhr.onreadystatechange = function () {
                    if (xhr.readyState === XMLHttpRequest.DONE) {
                        if (xhr.status === 200) {
                            document.querySelector("#dataset_response").innerHTML = JSON.stringify(JSON.parse(xhr.responseText), undefined, 2);
                            document.querySelector("#dataset_visualize").innerHTML = `<img src="data:image/png;base64, ${JSON.parse(xhr.responseText).target_function_jpg_bytes}" style="width: 100%;">`;
                        } else {
                            document.querySelector("#dataset_response").innerHTML = `Ошибка запроса: ${xhr.status}`;
                        }
                    }
                };
            }
        </script>
    </div>
</div>
{% endblock content %}